### ISSUE TITLE
running docker image in Windows10 64-bit returns an error

### ISSUE THREAD

**Issue by gmichel-SMU** [datascienceworkshops/dockerfiles#5]
I'm trying to run the docker image locally in Windows 10 box but the command is returning error:

docker run --rm -itv`pwd`:/data datascienceworkshops/data-science-at-the-command-line
docker: Error response from daemon: create `pwd`: "`pwd`" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by Crevax** [comment]
What does just running `pwd` output?

**Comment by gmichel-SMU** [comment]
It is running if I run from the drive root as following:

C:\>docker run --rm -itv "pwd":/data datascienceworkshops/data-science-at-the-command-line
[/data]$

**Comment by Crevax** [comment]
`` `pwd` `` Is just a command to print out the current working directory (what are you entering your command in anyway? Powershell? CMD? Git Bash)? So whatever directory you original ran the command from contained a character that docker does't like.

**Comment by jeroenjanssens** [comment]
I have clarified this in the text, see https://www.datascienceatthecommandline.com/chapter-2-getting-started.html#docker-image and jeroenjanssens/data-science-at-the-command-line@de9654ab30d438ef4fda7fa156eb83570deb947a
